# Load the WordClass class hierarchy
# Algorithm: load the leaf classes from hierarchy

require_relative 'adjective'
require_relative 'adverb'
require_relative 'adverb_not'
require_relative 'adverb_there'
require_relative 'auxiliary_be'
require_relative 'auxiliary_do'
require_relative 'cardinal'
require_relative 'comparative_particle'
require_relative 'common_noun'
require_relative 'degree_adverb'
require_relative 'pronoun'
require_relative 'proper_noun'
require_relative 'irregular_verb'
require_relative 'irregular_verb_be'
require_relative 'definite_article'
require_relative 'demonstrative_determiner'
require_relative 'demonstrative_pronoun'
require_relative 'indefinite_pronoun'
require_relative 'indefinite_quantifier'
require_relative 'linking_adverb'
require_relative 'preposition'
require_relative 'preposition_of'
require_relative 'preposition_than'
require_relative 'regular_verb'
require_relative 'subordinating_conjunction'