AllCops:
  Exclude:
    - 'exp/**/*'
    - 'demo/**/*'
  NewCops: enable
  SuggestExtensions: false

Gemspec/DevelopmentDependencies:
  EnforcedStyle: gemspec

Layout/ArgumentAlignment:
  Enabled: false

Layout/ArrayAlignment:
  Enabled: true
  EnforcedStyle: with_fixed_indentation

Layout/CaseIndentation:
  Enabled: false

Layout/ClosingHeredocIndentation:
  Enabled: false

Layout/CommentIndentation:
  Enabled: false

Layout/ElseAlignment:
  Enabled: false

Layout/EmptyLines:
  Enabled: false

Layout/EndAlignment:
  Enabled: false

Layout/EndOfLine:
  Enabled: true
  EnforcedStyle: lf

Layout/FirstArgumentIndentation:
  Enabled: false

Layout/HashAlignment:
  Enabled: false

Layout/IndentationWidth:
  Enabled: false

Layout/IndentationConsistency:
  Enabled: true

Layout/HeredocIndentation:
  Enabled: false

Layout/MultilineMethodCallBraceLayout:
  Enabled: true
  EnforcedStyle: same_line

Lint/Void:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Enabled: true
  Max: 350

Metrics/BlockNesting:
  Enabled: true
  Max: 5

Metrics/ClassLength:
  Enabled: true
  Max: 450

Metrics/CyclomaticComplexity:
  Enabled: false

Layout/LineLength:
  Enabled: false
  Max: 90

Metrics/MethodLength:
  Enabled: true
  Max: 60

Metrics/ModuleLength:
  Enabled: true
  Max: 500

Metrics/PerceivedComplexity:
  Enabled: false

Naming/BlockForwarding:
  EnforcedStyle: explicit
  BlockForwardingName: aBlock

Naming/ConstantName:
  Enabled: false

Naming/ClassAndModuleCamelCase:
  Enabled: false

Naming/MethodParameterName:
  Enabled: false

Naming/MethodName:
  Enabled: false

Naming/VariableName:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Style/BarePercentLiterals:
  Enabled: false

Style/BlockComments:
  Enabled: false

Style/CharacterLiteral:
  Enabled: false

Style/ClassCheck:
  Enabled: false

Style/ClassVars:
  Enabled: false

Style/ColonMethodCall:
  Enabled: false

Style/CommentAnnotation:
  Enabled: false

Style/CommentedKeyword:
  Enabled: false

Style/ConditionalAssignment:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/ExpandPathArguments:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/InverseMethods:
  Enabled: false

Style/MissingRespondToMissing:
  Enabled: false

Style/Next:
  Enabled: false

Style/NumericLiterals:
  Enabled: false

Style/QuotedSymbols:
  Enabled: true

Style/RedundantReturn:
  Enabled: false

Style/RegexpLiteral:
  Enabled: false

Style/PercentLiteralDelimiters:
  Enabled: false

Style/StderrPuts:
  Enabled: false

# Calling super is mandatory for WClass subclasses, therefore we disable this cop
Style/SuperArguments:
  Enabled: false

Style/TernaryParentheses:
  Enabled: false

Style/UnlessElse:
  Enabled: false

## Optional rubocop-rspec plugin rule checking
RSpec/ContextWording:
  Enabled: false

RSpec/DescribeClass:
  Enabled: false

RSpec/EmptyExampleGroup:
  Enabled: false

RSpec/ExampleLength:
  Max: 60

RSpec/IndexedLet:
  Enabled: false

RSpec/MultipleExpectations:
  Max: 25

RSpec/MultipleMemoizedHelpers:
  Max: 35

RSpec/NoExpectationExample:
  Enabled: false

RSpec/RepeatedDescription:
  Enabled: false

RSpec/RepeatedExample:
  Enabled: false

RSpec/RepeatedExampleGroupDescription:
  Enabled: false

RSpec/VerifiedDoubles:
  Enabled: false