language: ruby
dist: trusty

before_install:
  - gem update --system
  - gem install bundler  

script:
  - bundle exec rake
  
rvm:
  - 2.6.3
  - 2.5.5
  - 2.4.6
  - jruby-9.1.9.0
  
matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-9.1.9.0
    - rvm: jruby-head

# whitelist
branches:
  only:
    - master
